# Generated by Django 3.2 on 2021-04-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
    ]
