# Generated by Django 3.2 on 2021-04-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgapp', '0003_patientprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
    ]
