# Generated by Django 3.2 on 2021-04-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgapp', '0004_remove_patientprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
