# Generated by Django 3.2 on 2021-04-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgapp', '0005_alter_patientprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='hr',
            field=models.CharField(blank=True, default=[214], max_length=300, null=True, verbose_name='databaseURL'),
        ),
    ]
