# Generated by Django 3.2 on 2021-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgapp', '0006_patientprofile_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='hr',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
