# Generated by Django 3.2 on 2021-04-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgapp', '0009_auto_20210428_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='end_min',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='start_min',
        ),
    ]
