# Generated by Django 3.2 on 2021-05-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgapp', '0011_patientprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
